info:
  contact: {}
paths:
  /v1/api:
    get:
      description: Return API
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return API
      tags:
      - api
  /v1/api/{service}:
    get:
      description: Returns service status
      parameters:
      - description: required
        in: path
        name: service
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return service status
      tags:
      - api
  /v1/api/restart:
    post:
      description: Restarts service
      parameters:
      - description: required
        in: body
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Restart service
      tags:
      - api
  /v1/api/start:
    post:
      description: Starts service
      parameters:
      - description: required
        in: body
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Start service
      tags:
      - api
  /v1/api/stop:
    post:
      description: Stops service
      parameters:
      - description: required
        in: body
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Stop service
      tags:
      - api
  /v1/lookup/car-models:
    get:
      description: Return CarModels Lookup
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return CarModels Lookup
      tags:
      - Lookup
  /v1/lookup/cup-categories:
    get:
      description: Return CupCategories Lookup
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return CupCategories Lookup
      tags:
      - Lookup
  /v1/lookup/driver-categories:
    get:
      description: Return DriverCategories Lookup
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return DriverCategories Lookup
      tags:
      - Lookup
  /v1/lookup/session-types:
    get:
      description: Return SessionTypes Lookup
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return SessionTypes Lookup
      tags:
      - Lookup
  /v1/lookup/tracks:
    get:
      description: Return Tracks Lookup
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return Tracks Lookup
      tags:
      - Lookup
  /v1/server:
    get:
      description: Return Servers
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return Servers
      tags:
      - Server
  /v1/server/{id}/config:
    get:
      description: Return Config files
      parameters:
      - description: required
        in: path
        name: id
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return Configs
      tags:
      - Config
  /v1/server/{id}/config/{file}:
    get:
      description: Returns Config file
      parameters:
      - description: required
        in: path
        name: id
        required: true
        type: number
      - description: required
        in: path
        name: file
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Return Config file
      tags:
      - Config
    put:
      description: Updates config
      parameters:
      - description: required
        in: path
        name: id
        required: true
        type: number
      - description: required
        in: path
        name: file
        required: true
        type: string
      - description: required
        in: body
        name: content
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Update config
      tags:
      - Config
swagger: "2.0"
